### ISSUE TITLE
Add support of variables

### ISSUE THREAD

**Issue by AlexanderIakovlev** [perses/metrics-usage#12]
After configuring grafana collector, metrics-usage tool produces errors like that:
```
ERRO[2024-11-05T15:29:08+02:00] failed to extract metric names from PromQL expression in the panel "Service details" for the dashboard Collection/kXFGDWVIk  collector=grafana error="1:168: parse error: unexpected character: '$'"
ERRO[2024-11-05T15:29:08+02:00] failed to extract metric names from PromQL expression in the panel "Cloud Resource" for the dashboard Collection/kXFGDWVIk  collector=grafana error="1:208: parse error: unexpected character: '$'"
```
We rely heavily on variables, e.x.:
`service_status{env=~"$env",region=~"$region"}`

Automation doesn't fail immediately, but skip query with error.

**Comment by Nexucis** [comment]
If the variable expression is the one you are sharing, it should actually work.

Would you mind to share a small dashboard that reproduces this issue please ?

**Comment by Nexucis** [comment]
that's perfect thank you very much @AlexanderIakovlev. I will make a patch thanks to that ! 

> In exposed API I can't see metric service_color, that's why I thought it's skip it.

To display the metrics you need to activate the `metrics_collector`, the other collectors are there to collect the usage of the metrics.

If you can't see the metrics, that means the `metrics_collector` is not activated or it doesn't find the metrics from Prometheus or Thanos

**Comment by AlexanderIakovlev** [comment]
`metrics_collector` and `rules_collector` activated. This is another big question to me. We have around 100 millions active timeseries, but only 250k rows in the result json document. Want to investigate it as well.

**Comment by AlexanderIakovlev** [comment]
Thanks for your help @Nexucis . In the meantime I did research about metrics count and your tool works great. I just made not proper requests to `/api/v1/label/ API` using `end` and `start` parameters during manual verification. So it's not a problem 🎉

**Comment by Nexucis** [comment]
perfect @AlexanderIakovlev :). On my side I have fixed various issue when parsing grafana dashboards, should be better now.

will release a patch asap

**Comment by aiakovlev-twilio** [comment]
@Nexucis  I tested the new version and see positive changes. Not sure that you have appetite to make it better, but I still see many of the same errors. e.x.
```
ERRO[2024-11-06T18:14:38+02:00] failed to extract metric names from PromQL expression in the panel "Spans ${metric:text}" for the dashboard OpenTelemetry Collector import 04.11.24/BKf2sowmj  collector=grafana error="1:5: parse error: unexpected character: '$'"
ERRO[2024-11-06T18:14:38+02:00] failed to extract metric names from PromQL expression in the panel "Spans ${metric:text}" for the dashboard OpenTelemetry Collector import 04.11.24/BKf2sowmj  collector=grafana error="1:5: parse error: unexpected character: '$'"
ERRO[2024-11-06T18:14:38+02:00] failed to extract metric names from PromQL expression in the panel "Metric Points ${metric:text}" for the dashboard OpenTelemetry Collector import 04.11.24/BKf2sowmj  collector=grafana error="1:5: parse error: unexpected character: '$'"
ERRO[2024-11-06T18:14:38+02:00] failed to extract metric names from PromQL expression in the panel "Metric Points ${metric:text}" for the dashboard OpenTelemetry Collector import 04.11.24/BKf2sowmj  collector=grafana error="1:5: parse error: unexpected character: '$'"
ERRO[2024-11-06T18:14:38+02:00] failed to extract metric names from PromQL expression in the panel "Log Records ${metric:text}" for the dashboard OpenTelemetry Collector import 04.11.24/BKf2sowmj  collector=grafana error="1:5: parse error: unexpected character: '$'"
ERRO[2024-11-06T18:14:38+02:00] failed to extract metric names from PromQL expression in the panel "Log Records ${metric:text}" for the dashboard OpenTelemetry Collector import 04.11.24/BKf2sowmj  collector=grafana error="1:5: parse error: unexpected character: '$'"
ERRO[2024-11-06T18:14:38+02:00] failed to extract metric names from PromQL expression in the panel "Spans ${metric:text}" for the dashboard OpenTelemetry Collector import 04.11.24/BKf2sowmj  collector=grafana error="1:5: parse error: unexpected character: '$'"
ERRO[2024-11-06T18:14:38+02:00] failed to extract metric names from PromQL expression in the panel "Spans ${metric:text}" for the dashboard OpenTelemetry Collector import 04.11.24/BKf2sowmj  collector=grafana error="1:5: parse error: unexpected character: '$'"
ERRO[2024-11-06T18:14:38+02:00] failed to extract metric names from PromQL expression in the panel "Spans ${metric:text}" for the dashboard OpenTelemetry Collector import 04.11.24/BKf2sowmj  collector=grafana error="1:5: parse error: unexpected character: '$'"
ERRO[2024-11-06T18:14:38+02:00] failed to extract metric names from PromQL expression in the panel "Metric Points ${metric:text}" for the dashboard OpenTelemetry Collector import 04.11.24/BKf2sowmj  collector=grafana error="1:5: parse error: unexpected character: '$'"
ERRO[2024-11-06T18:14:38+02:00] failed to extract metric names from PromQL expression in the panel "Metric Points ${metric:text}" for the dashboard OpenTelemetry Collector import 04.11.24/BKf2sowmj  collector=grafana error="1:5: parse error: unexpected character: '$'"
ERRO[2024-11-06T18:14:38+02:00] failed to extract metric names from PromQL expression in the panel "Metric Points ${metric:text}" for the dashboard OpenTelemetry Collector import 04.11.24/BKf2sowmj  collector=grafana error="1:5: parse error: unexpected character: '$'"
ERRO[2024-11-06T18:14:38+02:00] failed to extract metric names from PromQL expression in the panel "Log Records ${metric:text}" for the dashboard OpenTelemetry Collector import 04.11.24/BKf2sowmj  collector=grafana error="1:5: parse error: unexpected character: '$'"
ERRO[2024-11-06T18:14:38+02:00] failed to extract metric names from PromQL expression in the panel "Log Records ${metric:text}" for the dashboard OpenTelemetry Collector import 04.11.24/BKf2sowmj  collector=grafana error="1:5: parse error: unexpected character: '$'"
ERRO[2024-11-06T18:14:38+02:00] failed to extract metric names from PromQL expression in the panel "Log Records ${metric:text}" for the dashboard OpenTelemetry Collector import 04.11.24/BKf2sowmj  collector=grafana error="1:5: parse error: unexpected character: '$'"
ERRO[2024-11-06T18:14:38+02:00] failed to extract metric names from PromQL expression in the panel "Batch Metrics 1" for the dashboard OpenTelemetry Collector import 04.11.24/BKf2sowmj  collector=grafana error="1:5: parse error: unexpected character: '$'"
ERRO[2024-11-06T18:14:38+02:00] failed to extract metric names from PromQL expression in the panel "Batch Metrics 1" for the dashboard OpenTelemetry Collector import 04.11.24/BKf2sowmj  collector=grafana error="1:5: parse error: unexpected character: '$'"
ERRO[2024-11-06T18:14:38+02:00] failed to extract metric names from PromQL expression in the panel "Batch Metrics 2" for the dashboard OpenTelemetry Collector import 04.11.24/BKf2sowmj  collector=grafana error="1:5: parse error: unexpected character: '$'"
ERRO[2024-11-06T18:14:38+02:00] failed to extract metric names from PromQL expression in the panel "Batch Metrics 2" for the dashboard OpenTelemetry Collector import 04.11.24/BKf2sowmj  collector=grafana error="1:5: parse error: unexpected character: '$'"
ERRO[2024-11-06T18:14:38+02:00] failed to extract metric names from PromQL expression in the panel "Spans ${metric:text}" for the dashboard OpenTelemetry Collector import 04.11.24/BKf2sowmj  collector=grafana error="1:5: parse error: unexpected character: '$'"
ERRO[2024-11-06T18:14:38+02:00] failed to extract metric names from PromQL expression in the panel "Spans ${metric:text}" for the dashboard OpenTelemetry Collector import 04.11.24/BKf2sowmj  collector=grafana error="1:5: parse error: unexpected character: '$'"
ERRO[2024-11-06T18:14:38+02:00] failed to extract metric names from PromQL expression in the panel "Spans ${metric:text}" for the dashboard OpenTelemetry Collector import 04.11.24/BKf2sowmj  collector=grafana error="1:5: parse error: unexpected character: '$'"
ERRO[2024-11-06T18:14:38+02:00] failed to extract metric names from PromQL expression in the panel "Metric Points ${metric:text}" for the dashboard OpenTelemetry Collector import 04.11.24/BKf2sowmj  collector=grafana error="1:5: parse error: unexpected character: '$'"
ERRO[2024-11-06T18:14:38+02:00] failed to extract metric names from PromQL expression in the panel "Metric Points ${metric:text}" for the dashboard OpenTelemetry Collector import 04.11.24/BKf2sowmj  collector=grafana error="1:5: parse error: unexpected character: '$'"
ERRO[2024-11-06T18:14:38+02:00] failed to extract metric names from PromQL expression in the panel "Metric Points ${metric:text}" for the dashboard OpenTelemetry Collector import 04.11.24/BKf2sowmj  collector=grafana error="1:5: parse error: unexpected character: '$'"
ERRO[2024-11-06T18:14:38+02:00] failed to extract metric names from PromQL expression in the panel "Log Records ${metric:text}" for the dashboard OpenTelemetry Collector import 04.11.24/BKf2sowmj  collector=grafana error="1:5: parse error: unexpected character: '$'"
ERRO[2024-11-06T18:14:38+02:00] failed to extract metric names from PromQL expression in the panel "Log Records ${metric:text}" for the dashboard OpenTelemetry Collector import 04.11.24/BKf2sowmj  collector=grafana error="1:5: parse error: unexpected character: '$'"
ERRO[2024-11-06T18:14:38+02:00] failed to extract metric names from PromQL expression in the panel "Log Records ${metric:text}" for the dashboard OpenTelemetry Collector import 04.11.24/BKf2sowmj  collector=grafana error="1:5: parse error: unexpected character: '$'"
ERRO[2024-11-06T18:14:38+02:00] failed to extract metric names from PromQL expression in the panel "CPU Usage" for the dashboard OpenTelemetry Collector import 04.11.24/BKf2sowmj  collector=grafana error="1:37: parse error: unexpected character: '$'"
ERRO[2024-11-06T18:14:38+02:00] failed to extract metric names from PromQL expression in the panel "CPU Usage" for the dashboard OpenTelemetry Collector import 04.11.24/BKf2sowmj  collector=grafana error="1:37: parse error: unexpected character: '$'"
ERRO[2024-11-06T18:14:38+02:00] failed to extract metric names from PromQL expression in the panel "CPU Usage" for the dashboard OpenTelemetry Collector import 04.11.24/BKf2sowmj  collector=grafana error="1:37: parse error: unexpected character: '$'"
```

These errors only for https://grafana.com/grafana/dashboards/15983-opentelemetry-collector/ default dashboard.

**Comment by Nexucis** [comment]
I can give a try for sure :).

But I have already made a bunch of manual check about errors appearing after the v0.3.1 and for the moment I didn't see what I could do.

For example, error can happen if you have a variable in the middle of a metric name. This is something that cannot be extracted.

I am not saying that I cannot improve the code, just at some point, there will be errors just because the query expression is in a bad shape and there is nothing the tool can do about it :)

**Comment by Nexucis** [comment]
I take a look at the dashboard you shared @aiakovlev-twilio and indeed there is nothing I can do.

In this dashboard, there is (for example) this expression: 

`"sum(${metric:value}(otelcol_processor_accepted_spans${suffix}{processor=~\"$processor\",job=\"$job\"}[$__rate_interval])) by (processor $grouping)",`

As you can see `${suffix}` is in the name of the metric so it's impossible to extract

**Comment by Nexucis** [comment]
ideally when such situation happens (aka having a variable into the metric_name), the code shouldn't not log an error but more a warning or an info, explaining the situation.

**Comment by Nexucis** [comment]
just FYI, I am re-implementing a small parser to extract the metric with variable inside. And first tests gave promising results. I will certainly deliver it next week.

**Comment by Nexucis** [comment]
(don't have anymore any error with the opentelemetry dashboard)
